### ISSUE TITLE
How does this package work

### ISSUE THREAD

**Issue by Tricked-dev** [SatvikVejendla/Neural-Network-Node#1]
when it try to use it i just get this error
```ts
(node:6549) UnhandledPromiseRejectionWarning: /home/tricked/coding/Malil/node_modules/neural-network-node/utils/networks/DFF/npm/DFF.js:1
import Matrix from "../../../global/html/Matrix.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/tricked/coding/Malil/node_modules/neural-network-node/src/npm/index.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
(Use `node --trace-warnings ...` to show where the warning was created)
```
tried using DFF/standart to make the class didnt work either any idea what might be up?

**Comment by SatvikVejendla** [comment]
Can you attach your code that you used? Try copy pasting the HTML "script" tag that you used to import the module.

**Comment by SatvikVejendla** [comment]
It should be fixed now. I accidentally put the HTML files in the NPM folder and that caused your error. Install the package again and it should work

**Comment by SatvikVejendla** [comment]
Does it work now?

**Comment by Tricked-dev** [comment]
yeah thanks for fixing it
